name: Release

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version number'
        required: true

jobs:
  build:
    name: Build release
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./KansasPPDMLoaderConsole/KansasPPDMLoaderConsole.csproj -c Release --self-contained true -r win-x64 -p:PublishSingleFile=true

      - name: View content
        run: dir ./KansasPPDMLoaderConsole/bin/Release/net8.0/win-x64/publish

      - name: Upload KansasPPDMLoader Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: KansasPPDMLoader
          path: ./KansasPPDMLoaderConsole/bin/Release/net8.0/win-x64/publish/KansasPPDMLoaderConsole.exe

      - name: Create release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.versionNumber }}
          release_name: Release v${{ github.event.inputs.versionNumber }}
          draft: false
          prerelease: false

      - name: Download KansasPPDMLoader artifact
        uses: actions/download-artifact@v3
        with:
          name: KansasPPDMLoader

      - name: Install GitHub CLI
        uses: cli/cli-action@v2

      - name: Authenticate GitHub CLI
        run: gh auth setup-git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload KansasPPDMLoader release asset
        run: gh release upload v${{ github.event.inputs.versionNumber }} KansasPPDMLoader/KansasPPDMLoaderConsole.exe --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
